version: '3.4'

services:
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: always
    ports:
      - 6378:6378

  arq:
    build:
      context: .
      dockerfile: docker/arq/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
        - redis

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - redis
