"""empty message

Revision ID: 04a96ac886c2
Revises: 
Create Date: 2023-08-24 17:41:30.305206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a96ac886c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('ban', sa.Boolean(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('last_call', sa.DateTime(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=False),
    sa.Column('session_string', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot'))
    )
    op.create_table('proxy',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxy'))
    )
    op.create_table('user',
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('subscriberstask',
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('pause', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('next_start_date', sa.DateTime(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], name=op.f('fk_subscriberstask_user_fk_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriberstask'))
    )
    op.create_table('viewstask',
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('pause', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('next_start_date', sa.DateTime(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], name=op.f('fk_viewstask_user_fk_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewstask'))
    )
    op.create_table('subscriberstarget',
    sa.Column('task_fk', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('count_done', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_fk'], ['subscriberstask.id'], name=op.f('fk_subscriberstarget_task_fk_subscriberstask'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriberstarget'))
    )
    op.create_table('viewstarget',
    sa.Column('task_fk', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('count_done', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_fk'], ['viewstask.id'], name=op.f('fk_viewstarget_task_fk_viewstask'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewstarget'))
    )
    op.create_table('subscribersusedbot',
    sa.Column('bot_fk', sa.Integer(), nullable=False),
    sa.Column('target_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bot_fk'], ['bot.id'], name=op.f('fk_subscribersusedbot_bot_fk_bot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_fk'], ['subscriberstarget.id'], name=op.f('fk_subscribersusedbot_target_fk_subscriberstarget'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribersusedbot'))
    )
    op.create_table('viewsusedbot',
    sa.Column('bot_fk', sa.Integer(), nullable=False),
    sa.Column('target_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bot_fk'], ['bot.id'], name=op.f('fk_viewsusedbot_bot_fk_bot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_fk'], ['viewstarget.id'], name=op.f('fk_viewsusedbot_target_fk_viewstarget'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewsusedbot'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewsusedbot')
    op.drop_table('subscribersusedbot')
    op.drop_table('viewstarget')
    op.drop_table('subscriberstarget')
    op.drop_table('viewstask')
    op.drop_table('subscriberstask')
    op.drop_table('user')
    op.drop_table('proxy')
    op.drop_table('bot')
    # ### end Alembic commands ###
