"""empty message

Revision ID: 04e1f508c3ae
Revises: 4ec54d7c6bbc
Create Date: 2023-08-09 21:32:17.588123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e1f508c3ae'
down_revision = '4ec54d7c6bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiple_task',
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('views', sa.Boolean(), nullable=False),
    sa.Column('reactions', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('pause', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('count_done', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('next_start_date', sa.DateTime(), nullable=False),
    sa.Column('done_in_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiple_task')
    # ### end Alembic commands ###
