"""empty message

Revision ID: 083ece267267
Revises: e3ecca5b19ef
Create Date: 2023-09-03 17:16:15.141896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083ece267267'
down_revision = 'e3ecca5b19ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactionstask',
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('pause', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('next_start_date', sa.DateTime(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['user.id'], name=op.f('fk_reactionstask_user_fk_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactionstask'))
    )
    op.create_table('reactionstarget',
    sa.Column('task_fk', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('count_done', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_fk'], ['reactionstask.id'], name=op.f('fk_reactionstarget_task_fk_reactionstask'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactionstarget'))
    )
    op.create_table('reactionsusedbot',
    sa.Column('bot_fk', sa.Integer(), nullable=False),
    sa.Column('target_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bot_fk'], ['bot.id'], name=op.f('fk_reactionsusedbot_bot_fk_bot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_fk'], ['reactionstarget.id'], name=op.f('fk_reactionsusedbot_target_fk_reactionstarget'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactionsusedbot'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactionsusedbot')
    op.drop_table('reactionstarget')
    op.drop_table('reactionstask')
    # ### end Alembic commands ###
