"""empty message

Revision ID: 0924a360c667
Revises: ceb6467099a7
Create Date: 2023-08-11 01:35:41.938599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0924a360c667'
down_revision = 'ceb6467099a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiple_task', sa.Column('last_date_start', sa.DateTime(), nullable=False))
    op.add_column('multiple_task', sa.Column('delay', sa.Integer(), nullable=False))
    op.add_column('multiple_task', sa.Column('busy', sa.Boolean(), nullable=False))
    op.drop_column('multiple_task', 'next_start_date')
    op.drop_column('multiple_task', 'done_in_hour')
    op.add_column('subscribers_task', sa.Column('last_date_start', sa.DateTime(), nullable=False))
    op.add_column('subscribers_task', sa.Column('delay', sa.Integer(), nullable=False))
    op.add_column('subscribers_task', sa.Column('busy', sa.Boolean(), nullable=False))
    op.drop_column('subscribers_task', 'next_start_date')
    op.drop_column('subscribers_task', 'done_in_hour')
    op.add_column('views_task', sa.Column('last_date_start', sa.DateTime(), nullable=False))
    op.add_column('views_task', sa.Column('delay', sa.Integer(), nullable=False))
    op.add_column('views_task', sa.Column('busy', sa.Boolean(), nullable=False))
    op.drop_column('views_task', 'next_start_date')
    op.drop_column('views_task', 'done_in_hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views_task', sa.Column('done_in_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('views_task', sa.Column('next_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('views_task', 'busy')
    op.drop_column('views_task', 'delay')
    op.drop_column('views_task', 'last_date_start')
    op.add_column('subscribers_task', sa.Column('done_in_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscribers_task', sa.Column('next_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('subscribers_task', 'busy')
    op.drop_column('subscribers_task', 'delay')
    op.drop_column('subscribers_task', 'last_date_start')
    op.add_column('multiple_task', sa.Column('done_in_hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('multiple_task', sa.Column('next_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('multiple_task', 'busy')
    op.drop_column('multiple_task', 'delay')
    op.drop_column('multiple_task', 'last_date_start')
    # ### end Alembic commands ###
