"""empty message

Revision ID: 0a4087ae6ae1
Revises: f68d6d6aff73
Create Date: 2023-08-02 23:40:04.344188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4087ae6ae1'
down_revision = 'f68d6d6aff73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
