"""empty message

Revision ID: 24d218210ee8
Revises: 0a4087ae6ae1
Create Date: 2023-08-02 23:42:33.642298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d218210ee8'
down_revision = '0a4087ae6ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
