"""empty message

Revision ID: 413628e5dab4
Revises: 6e0b3f1d9f00
Create Date: 2023-07-29 03:26:38.253515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413628e5dab4'
down_revision = '6e0b3f1d9f00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('work', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'work')
    # ### end Alembic commands ###
