"""empty message

Revision ID: 472f72081903
Revises: 04e1f508c3ae
Create Date: 2023-08-09 22:14:35.330366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f72081903'
down_revision = '04e1f508c3ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('multiple_task', 'avatar')
    op.drop_column('multiple_task', 'link')
    op.drop_column('subscribers_task', 'avatar')
    op.drop_column('subscribers_task', 'link')
    op.drop_column('views_task', 'avatar')
    op.drop_column('views_task', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views_task', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('views_task', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscribers_task', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscribers_task', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('multiple_task', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('multiple_task', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('channels')
    # ### end Alembic commands ###
