"""empty message

Revision ID: 5acb5846bc3c
Revises: 6cf81d6b032e
Create Date: 2023-09-03 19:33:09.949101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acb5846bc3c'
down_revision = '6cf81d6b032e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
