"""empty message

Revision ID: 6cf81d6b032e
Revises: b15716909343
Create Date: 2023-09-03 19:30:01.973343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf81d6b032e'
down_revision = 'b15716909343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactionstask', sa.Column('reactions', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactionstask', 'reactions')
    # ### end Alembic commands ###
