"""empty message

Revision ID: 6d61ba60f53f
Revises: 0924a360c667
Create Date: 2023-08-11 02:15:53.532491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d61ba60f53f'
down_revision = '0924a360c667'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
