"""empty message

Revision ID: 6f4e83a76838
Revises: 24d218210ee8
Create Date: 2023-08-08 00:52:24.858906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4e83a76838'
down_revision = '24d218210ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers_tasks', sa.Column('completed_in_hour', sa.Integer(), nullable=True))
    op.add_column('views_tasks', sa.Column('completed_in_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views_tasks', 'completed_in_hour')
    op.drop_column('subscribers_tasks', 'completed_in_hour')
    # ### end Alembic commands ###
