"""empty message

Revision ID: 93f508f0546b
Revises: 413628e5dab4
Create Date: 2023-07-31 16:05:25.100821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f508f0546b'
down_revision = '413628e5dab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('busy', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'busy')
    # ### end Alembic commands ###
