"""empty message

Revision ID: 9972a7d420a4
Revises: 93f508f0546b
Create Date: 2023-07-31 17:37:37.022467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9972a7d420a4'
down_revision = '93f508f0546b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers_tasks', 'in_progress')
    op.drop_column('subscribers_tasks', 'completed')
    op.drop_column('views_tasks', 'in_progress')
    op.drop_column('views_tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views_tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('views_tasks', sa.Column('in_progress', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscribers_tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('subscribers_tasks', sa.Column('in_progress', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
