"""empty message

Revision ID: b15716909343
Revises: 083ece267267
Create Date: 2023-09-03 17:24:32.006413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15716909343'
down_revision = '083ece267267'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactionstask', 'limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactionstask', sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
