"""empty message

Revision ID: dbf6995fe2f2
Revises: 9972a7d420a4
Create Date: 2023-07-31 19:05:19.815725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf6995fe2f2'
down_revision = '9972a7d420a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers_tasks', 'skip_bots')
    op.drop_column('views_tasks', 'skip_bots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('views_tasks', sa.Column('skip_bots', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscribers_tasks', sa.Column('skip_bots', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
