"""empty message

Revision ID: e3ecca5b19ef
Revises: 04a96ac886c2
Create Date: 2023-08-24 17:42:39.152328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ecca5b19ef'
down_revision = '04a96ac886c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
