"""empty message

Revision ID: eebc08cb36cd
Revises: 6f4e83a76838
Create Date: 2023-08-08 12:26:29.989569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebc08cb36cd'
down_revision = '6f4e83a76838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers_tasks', sa.Column('next_start_date', sa.DateTime(), nullable=False))
    op.add_column('views_tasks', sa.Column('next_start_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views_tasks', 'next_start_date')
    op.drop_column('subscribers_tasks', 'next_start_date')
    # ### end Alembic commands ###
