"""empty message

Revision ID: f68d6d6aff73
Revises: e314a7380f16
Create Date: 2023-08-02 23:24:10.823210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68d6d6aff73'
down_revision = 'e314a7380f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers_tasks', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('subscribers_tasks', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('views_tasks', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('views_tasks', sa.Column('end_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('views_tasks', 'end_date')
    op.drop_column('views_tasks', 'start_date')
    op.drop_column('subscribers_tasks', 'end_date')
    op.drop_column('subscribers_tasks', 'start_date')
    # ### end Alembic commands ###
